version: '3.8'

services:
  discord-based-bot:
    image: corentinth/it-tools:latest
    environment:
      - CONFIG_FILE=config.yaml
    volumes:
      - /mnt/data/basedgpt:/app
    restart: unless-stopped